apiVersion: v2
version: 0.1.0
name: common
description: A Library Helm Chart for definitions that can be shared by Helm templates in other charts.
home: https://github.com/kubeshop/helm-charts/tree/main/charts/common
type: library
# This version number should be incremented each time the changes are made to the chart and its templates, including the app version.
annotations:
  category: Infrastructure
keywords:
  - common
  - helper
  - template
  - function
  - testkube
maintainers:
  - name: Testkube
    url: https://github.com/kubeshop/testkube
sources:
  - https://github.com/kubeshop/helm-charts
  - https://testkube.io/

appVersion: "0.1.0"