apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 1.17.62
appVersion: 1.17.62
dependencies:
  - name: global
    version: 0.1.2
    repository: "file://../global"
