apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 1.9.28
appVersion: 1.9.28
dependencies:
  - name: global
    version: 0.1.1
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
