apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 1.7.22
appVersion: 1.7.22
##Uncomment for local testing of testkube-api chart only
dependencies:
  - name: global
    version: 0.1.0
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
