apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 2.1.138
appVersion: 2.1.138
dependencies:
  - name: global
    version: 0.1.3
    repository: "file://../global"
