{{- if .Values.image.imageCredentials.registry -}}
apiVersion: v1
kind: Secret
metadata:
  name: registrykey-{{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
