{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "testkube-api.fullname" . }}
  labels: {{- include "global.labels.standard" . | nindent 4 }}
  {{- if .Values.autoscaling.labels }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.autoscaling.labels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.globalLabels }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.globalLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.autoscaling.annotations }}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.autoscaling.annotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.globalAnnotations }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.globalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "global.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ include "testkube-api.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
