apiVersion: v2
name: testkube-runner
description: A Helm chart for the Testkube's Runner Agent
type: application
version: 2.2.1
appVersion: 2.2.1
dependencies:
- name: global
  version: 0.1.3
  repository: "file://../global"
