apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cypress-executor
  namespace: {{ .Release.Namespace }}
spec:
  executor_type: job
  image: kubeshop/testkube-cypress-executor:0.6.9
  types:
  - cypress/project

---

apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: curl-executor
  namespace: {{ .Release.Namespace }}
spec:
  executor_type: job
  image: kubeshop/testkube-curl-executor:0.6.6
  types:
  - curl/test

---
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: postman-executor
  namespace: {{ .Release.Namespace }}
spec:
  executor_type: job
  image: kubeshop/testkube-postman-executor:0.6.7
  types:
  - postman/collection
