apiVersion: v2
name: testkube-operator
description: A Helm chart for the testkube-operator (installs needed CRDs only for now)
type: application
version: 2.1.115
appVersion: 2.1.114
dependencies:
  - name: global
    version: 0.1.3
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
