apiVersion: v2
name: testkube-operator
description: A Helm chart for the testkube-operator (installs needed CRDs only for now)
type: application
version: 1.10.5-beta002
appVersion: 1.10.5-beta002
dependencies:
  - name: global
    version: 0.1.1
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
