apiVersion: v2
name: testkube-operator
description: A Helm chart for the testkube-operator (installs needed CRDs only for now)
type: application
version: 1.8.2
appVersion: 1.8.2
dependencies:
  - name: global
    version: 0.1.0
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
