# .github/release.yml

changelog:
  categories:
    - title: ğŸ• Features
      labels:
        - feat
    - title: Bug fixes
      labels:
        - fix
    - title: Breaking Changes ğŸ› 
      labels:
        - breaking-change
    - title: ğŸ‘’ Dependencies
      labels:
        - deps
    - title: Documentation updates
      label: 
        - docs
    - title: Other Changes
      labels:
        - "*"
