apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executors-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: executors-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scripts-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scripts-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tests-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tests-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}
