apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "system:serviceaccount:default:api-server-chart" to manage secrets in the "default" namespace.
# You need to already have a Role named "scripts.operator.api-server" in that namespace.
kind: RoleBinding
metadata:
  name: manage-scripts-{{ .Release.Name }}
subjects:
# You can specify more than one "subject"
- kind: User
  name: "system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.fullnameOverride }}-{{ .Release.Name }}" # namespace to be parametrised
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: scripts.operator.api-server-{{ .Release.Name }} # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executors-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: executors-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}



---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tests-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-cluster-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: testkube-api-server-testkube
  namespace: {{ .Release.Namespace }}