apiVersion: v2
name: testkube
description: A Helm chart for testkube.
type: application
version: 0.5.84-testingg
dependencies:
- name: testkube-operator
  version: 0.5.8
  repository: https://kubeshop.github.io/helm-charts
- name: mongodb
  version: 10.0.0
  repository: https://charts.bitnami.com/bitnami
- name: api-server
  version: 0.5.51
  repository: https://kubeshop.github.io/helm-charts
- name: postman-executor
  version: 0.5.22
  repository: https://kubeshop.github.io/helm-charts
  condition: postman-executor.enabled
- name: cypress-executor
  version: 0.5.19
  repository: https://kubeshop.github.io/helm-charts
  condition: cypress-executor.enabled
- name: curl-executor
  version: 0.5.19
  repository: https://kubeshop.github.io/helm-charts
  condition: curl-executor.enabled
- name: testkube-dashboard
  version: 0.5.0
  repository: https://kubeshop.github.io/helm-charts
  condition: testkube-dashboard.enabled
